apiVersion: v1
kind: ServiceAccount
metadata:
  name: osac-aap-config-as-code
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "osac-aap.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: osac-aap-config-as-code-license-reader
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "osac-aap.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["{{ .Values.configAsCode.manifestSecret }}"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: osac-aap-config-as-code-license-reader
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "osac-aap.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: osac-aap-config-as-code-license-reader
subjects:
  - kind: ServiceAccount
    name: osac-aap-config-as-code
    namespace: {{ .Release.Namespace }}
