apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccounts.osacSa }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "osac-aap.labels" . | nindent 4 }}
secrets:
  - name: {{ .Values.serviceAccounts.osacSa }}-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.serviceAccounts.osacSa }}-{{ .Release.Namespace }}
  labels:
    {{- include "osac-aap.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccounts.osacSa }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.serviceAccounts.osacSa }}-token
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "osac-aap.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/service-account.name: {{ .Values.serviceAccounts.osacSa | quote }}
type: kubernetes.io/service-account-token
