// Code generated by MockGen. DO NOT EDIT.
// Source: ../../api/osac/private/v1/network_classes_service_grpc.pb.go
//
// Generated by this command:
//
//	mockgen -source=../../api/osac/private/v1/network_classes_service_grpc.pb.go -destination=network_classes_client_mock.go -package=tenant NetworkClassesClient
//

// Package tenant is a generated GoMock package.
package tenant

import (
	context "context"
	reflect "reflect"

	privatev1 "github.com/osac-project/osac/fulfillment-service/internal/api/osac/private/v1"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockNetworkClassesClient is a mock of NetworkClassesClient interface.
type MockNetworkClassesClient struct {
	ctrl     *gomock.Controller
	recorder *MockNetworkClassesClientMockRecorder
}

// MockNetworkClassesClientMockRecorder is the mock recorder for MockNetworkClassesClient.
type MockNetworkClassesClientMockRecorder struct {
	mock *MockNetworkClassesClient
}

// NewMockNetworkClassesClient creates a new mock instance.
func NewMockNetworkClassesClient(ctrl *gomock.Controller) *MockNetworkClassesClient {
	mock := &MockNetworkClassesClient{ctrl: ctrl}
	mock.recorder = &MockNetworkClassesClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNetworkClassesClient) EXPECT() *MockNetworkClassesClientMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockNetworkClassesClient) Create(ctx context.Context, in *privatev1.NetworkClassesCreateRequest, opts ...grpc.CallOption) (*privatev1.NetworkClassesCreateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(*privatev1.NetworkClassesCreateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockNetworkClassesClientMockRecorder) Create(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockNetworkClassesClient)(nil).Create), varargs...)
}

// Delete mocks base method.
func (m *MockNetworkClassesClient) Delete(ctx context.Context, in *privatev1.NetworkClassesDeleteRequest, opts ...grpc.CallOption) (*privatev1.NetworkClassesDeleteResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(*privatev1.NetworkClassesDeleteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockNetworkClassesClientMockRecorder) Delete(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockNetworkClassesClient)(nil).Delete), varargs...)
}

// Get mocks base method.
func (m *MockNetworkClassesClient) Get(ctx context.Context, in *privatev1.NetworkClassesGetRequest, opts ...grpc.CallOption) (*privatev1.NetworkClassesGetResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(*privatev1.NetworkClassesGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockNetworkClassesClientMockRecorder) Get(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockNetworkClassesClient)(nil).Get), varargs...)
}

// List mocks base method.
func (m *MockNetworkClassesClient) List(ctx context.Context, in *privatev1.NetworkClassesListRequest, opts ...grpc.CallOption) (*privatev1.NetworkClassesListResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].(*privatev1.NetworkClassesListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockNetworkClassesClientMockRecorder) List(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockNetworkClassesClient)(nil).List), varargs...)
}

// Signal mocks base method.
func (m *MockNetworkClassesClient) Signal(ctx context.Context, in *privatev1.NetworkClassesSignalRequest, opts ...grpc.CallOption) (*privatev1.NetworkClassesSignalResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Signal", varargs...)
	ret0, _ := ret[0].(*privatev1.NetworkClassesSignalResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Signal indicates an expected call of Signal.
func (mr *MockNetworkClassesClientMockRecorder) Signal(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signal", reflect.TypeOf((*MockNetworkClassesClient)(nil).Signal), varargs...)
}

// Update mocks base method.
func (m *MockNetworkClassesClient) Update(ctx context.Context, in *privatev1.NetworkClassesUpdateRequest, opts ...grpc.CallOption) (*privatev1.NetworkClassesUpdateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(*privatev1.NetworkClassesUpdateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockNetworkClassesClientMockRecorder) Update(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockNetworkClassesClient)(nil).Update), varargs...)
}

// MockNetworkClassesServer is a mock of NetworkClassesServer interface.
type MockNetworkClassesServer struct {
	ctrl     *gomock.Controller
	recorder *MockNetworkClassesServerMockRecorder
}

// MockNetworkClassesServerMockRecorder is the mock recorder for MockNetworkClassesServer.
type MockNetworkClassesServerMockRecorder struct {
	mock *MockNetworkClassesServer
}

// NewMockNetworkClassesServer creates a new mock instance.
func NewMockNetworkClassesServer(ctrl *gomock.Controller) *MockNetworkClassesServer {
	mock := &MockNetworkClassesServer{ctrl: ctrl}
	mock.recorder = &MockNetworkClassesServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNetworkClassesServer) EXPECT() *MockNetworkClassesServerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockNetworkClassesServer) Create(arg0 context.Context, arg1 *privatev1.NetworkClassesCreateRequest) (*privatev1.NetworkClassesCreateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.NetworkClassesCreateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockNetworkClassesServerMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockNetworkClassesServer)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockNetworkClassesServer) Delete(arg0 context.Context, arg1 *privatev1.NetworkClassesDeleteRequest) (*privatev1.NetworkClassesDeleteResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.NetworkClassesDeleteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockNetworkClassesServerMockRecorder) Delete(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockNetworkClassesServer)(nil).Delete), arg0, arg1)
}

// Get mocks base method.
func (m *MockNetworkClassesServer) Get(arg0 context.Context, arg1 *privatev1.NetworkClassesGetRequest) (*privatev1.NetworkClassesGetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.NetworkClassesGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockNetworkClassesServerMockRecorder) Get(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockNetworkClassesServer)(nil).Get), arg0, arg1)
}

// List mocks base method.
func (m *MockNetworkClassesServer) List(arg0 context.Context, arg1 *privatev1.NetworkClassesListRequest) (*privatev1.NetworkClassesListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.NetworkClassesListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockNetworkClassesServerMockRecorder) List(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockNetworkClassesServer)(nil).List), arg0, arg1)
}

// Signal mocks base method.
func (m *MockNetworkClassesServer) Signal(arg0 context.Context, arg1 *privatev1.NetworkClassesSignalRequest) (*privatev1.NetworkClassesSignalResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Signal", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.NetworkClassesSignalResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Signal indicates an expected call of Signal.
func (mr *MockNetworkClassesServerMockRecorder) Signal(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signal", reflect.TypeOf((*MockNetworkClassesServer)(nil).Signal), arg0, arg1)
}

// Update mocks base method.
func (m *MockNetworkClassesServer) Update(arg0 context.Context, arg1 *privatev1.NetworkClassesUpdateRequest) (*privatev1.NetworkClassesUpdateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.NetworkClassesUpdateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockNetworkClassesServerMockRecorder) Update(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockNetworkClassesServer)(nil).Update), arg0, arg1)
}

// mustEmbedUnimplementedNetworkClassesServer mocks base method.
func (m *MockNetworkClassesServer) mustEmbedUnimplementedNetworkClassesServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedNetworkClassesServer")
}

// mustEmbedUnimplementedNetworkClassesServer indicates an expected call of mustEmbedUnimplementedNetworkClassesServer.
func (mr *MockNetworkClassesServerMockRecorder) mustEmbedUnimplementedNetworkClassesServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedNetworkClassesServer", reflect.TypeOf((*MockNetworkClassesServer)(nil).mustEmbedUnimplementedNetworkClassesServer))
}

// MockUnsafeNetworkClassesServer is a mock of UnsafeNetworkClassesServer interface.
type MockUnsafeNetworkClassesServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeNetworkClassesServerMockRecorder
}

// MockUnsafeNetworkClassesServerMockRecorder is the mock recorder for MockUnsafeNetworkClassesServer.
type MockUnsafeNetworkClassesServerMockRecorder struct {
	mock *MockUnsafeNetworkClassesServer
}

// NewMockUnsafeNetworkClassesServer creates a new mock instance.
func NewMockUnsafeNetworkClassesServer(ctrl *gomock.Controller) *MockUnsafeNetworkClassesServer {
	mock := &MockUnsafeNetworkClassesServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeNetworkClassesServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeNetworkClassesServer) EXPECT() *MockUnsafeNetworkClassesServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedNetworkClassesServer mocks base method.
func (m *MockUnsafeNetworkClassesServer) mustEmbedUnimplementedNetworkClassesServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedNetworkClassesServer")
}

// mustEmbedUnimplementedNetworkClassesServer indicates an expected call of mustEmbedUnimplementedNetworkClassesServer.
func (mr *MockUnsafeNetworkClassesServerMockRecorder) mustEmbedUnimplementedNetworkClassesServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedNetworkClassesServer", reflect.TypeOf((*MockUnsafeNetworkClassesServer)(nil).mustEmbedUnimplementedNetworkClassesServer))
}
